#!/usr/bin/env python
"""Assemble EXPERIMENT_REPORT.md from the per-model result JSONs + training logs.

Runs at the end of run_experiments.sh so a complete report exists on disk even if the agent
session is paused. Robust to missing files (writes whatever stages have completed).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

sys.path.insert(0, "src")
from mids_plus.metrics import cross_set_summary

MODEL_ORDER = ["upstream", "mids_original_40k", "mids_pp_40k", "mids_original_full", "mids_pp_full"]
MODEL_LABEL = {
    "upstream": "Upstream MIDS (mids.pth, ~740k)",
    "mids_original_40k": "mids_original (40k/1ep)",
    "mids_pp_40k": "MIDS++ (40k/1ep)",
    "mids_original_full": "mids_original (full ~740k/1ep, my recipe)",
    "mids_pp_full": "MIDS++ (full ~740k/1ep)",
}


def load_results(exp_dir):
    res = {}
    rdir = os.path.join(exp_dir, "results")
    for f in os.listdir(rdir) if os.path.isdir(rdir) else []:
        if f.endswith(".json"):
            try:
                r = json.load(open(os.path.join(rdir, f)))
                tag = r["tag"]
                if tag in res:  # merge per_set across multiple files for the same model (eval2000 + buckets)
                    res[tag]["per_set"].update(r.get("per_set", {}))
                else:
                    res[tag] = r
            except Exception:
                pass
    return res


def last_epoch_line(log_path):
    if not os.path.exists(log_path):
        return "(log missing)"
    lines = open(log_path, errors="ignore").read().replace("\r", "\n").splitlines()
    ep = [l for l in lines if l.startswith("[epoch")]
    return ep[-1] if ep else "(no epoch summary yet)"


def fmt(x, scale=100):
    return f"{x*scale:5.2f}" if isinstance(x, (int, float)) and x == x else "  -  "


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--exp-dir", required=True)
    args = ap.parse_args()
    exp = args.exp_dir
    res = load_results(exp)
    out = []
    out.append("# MIDS++ experiment report\n")
    out.append("Auto-generated by build_report.py. Eval sets are the FFAA MIDS format; the 4-class "
               "logits are scored by the unchanged match-score selector. ACC/AUC/AP are binary "
               "real-vs-fake; `sACC` = std of per-bucket ACC (x100, lower=better).\n")

    # ---- Table A: in-distribution eval2000 ----
    out.append("## 1. In-distribution comparison on `eval2000.json` (same 2000-item subset)\n")
    out.append("| Model | ACC | AUC | AP | neutral-baseline |")
    out.append("| --- | --- | --- | --- | --- |")
    for tag in MODEL_ORDER:
        r = res.get(tag)
        if not r or "eval2000" not in r.get("per_set", {}):
            continue
        m = r["per_set"]["eval2000"]
        out.append(f"| {MODEL_LABEL[tag]} | {fmt(m['acc'])} | {fmt(m['auc'])} | {fmt(m['ap'])} | {fmt(m['neutral_acc'])} |")
    out.append("")

    # ---- Table B: cross-dataset buckets ----
    out.append("## 2. Cross-dataset robustness (per-bucket ACC + sACC)\n")
    out.append("Buckets are partitions of `mids_eval.json` by forgery-dataset token (intra-eval-set "
               "proxy; not true held-out datasets).\n")
    # collect bucket names (union, excluding eval2000), from any model that has buckets
    bucket_names = []
    for tag in MODEL_ORDER:
        r = res.get(tag)
        if r:
            for k in r.get("per_set", {}):
                if k != "eval2000" and k not in bucket_names:
                    bucket_names.append(k)
    if bucket_names:
        header = "| Model | " + " | ".join(bucket_names) + " | mean ACC | **sACC** |"
        out.append(header)
        out.append("| " + " --- |" * (len(bucket_names) + 3))
        for tag in MODEL_ORDER:
            r = res.get(tag)
            if not r:
                continue
            ps = r.get("per_set", {})
            accs = {b: ps[b]["acc"] for b in bucket_names if b in ps}
            if not accs:
                continue
            summ = cross_set_summary(accs)
            cells = [fmt(accs[b]) if b in accs else "  -  " for b in bucket_names]
            out.append(f"| {MODEL_LABEL[tag]} | " + " | ".join(cells) +
                       f" | {fmt(summ['mean_acc'])} | {summ['sacc']:.2f} |")
        out.append("")
        out.append("Per-bucket class balance (from MIDS++ full eval, real/fake counts):")
        rfull = res.get("mids_pp_full") or res.get("mids_pp_40k")
        if rfull:
            for b in bucket_names:
                if b in rfull["per_set"]:
                    m = rfull["per_set"][b]
                    out.append(f"- {b}: n={m['n']} (real {m['n_real']} / fake {m['n_fake']})")
        out.append("")
    else:
        out.append("_(bucket evals not yet available)_\n")

    # ---- training summaries ----
    out.append("## 3. Training summaries\n")
    out.append(f"- mids_original (40k): `{last_epoch_line(os.path.join(exp,'train_mids_original_40k.log'))}`")
    out.append(f"- mids_original (full ~740k): `{last_epoch_line(os.path.join(exp,'train_mids_original_full.log'))}`")
    out.append(f"- MIDS++ (full ~740k): `{last_epoch_line(os.path.join(exp,'train_mids_pp_full.log'))}`")
    out.append("- MIDS++ (40k) was trained earlier: see runs/real/train.log")
    out.append("")
    out.append("## 4. Notes / caveats\n")
    out.append("- Cross-dataset buckets are an intra-eval-set proxy; treat sACC as indicative.")
    out.append("- Single-class buckets have undefined AUC; ACC still meaningful (recall on that class).")
    out.append("- Training runs are 1 epoch each; not tuned. mids_original/mids_pp at 40k share data "
               "for a controlled A/B; mids_pp_full uses the whole train set.")

    report = "\n".join(out) + "\n"
    open(os.path.join(exp, "EXPERIMENT_REPORT.md"), "w").write(report)
    print(report)


if __name__ == "__main__":
    main()
